export const FULL_NAME = "fullName";
export const YEAR_OF_BIRTH = "yearOfBirth";
export const MAJORS = "majors";
export const STATUS = "status";
export const PAGINATION_CONSTANT = { page: 1, limit: 8 };
//#region get list student
export const HANDLE_GET_LIST_STUDENT = "HANDLE_GET_LIST_STUDENT";
export const HANDLE_GET_LIST_STUDENT_SUCCESS =
  "HANDLE_GET_LIST_STUDENT_SUCCESS";
export const HANDLE_GET_LIST_STUDENT_FAILED = "HANDLE_GET_LIST_STUDENT_FAILED";
//#endregion

//#region add student
export const HANDLE_ADD_STUDENT = "HANDLE_ADD_STUDENT";
export const HANDLE_ADD_STUDENT_SUCCESS = "HANDLE_ADD_STUDENT_SUCCESS";
export const HANDLE_ADD_STUDENT_FAILED = "HANDLE_ADD_STUDENT_FAILED";
//#endregion

//#region delete student
export const HANDLE_DELETE_STUDENT = "HANDLE_DELETE_STUDENT";
export const HANDLE_DELETE_STUDENT_SUCCESS = "HANDLE_DELETE_STUDENT_SUCCESS";
export const HANDLE_DELETE_STUDENT_FAILED = "HANDLE_DELETE_STUDENT_FAILED";
//#endregion

export const HANDLE_SORT_YEAROFBIRTH_INCREMENT =
  "HANDLE_SORT_YEAROFBIRTH_INCREMENT";
export const HANDLE_SORT_YEAROFBIRTH_DECREMENT =
  "HANDLE_SORT_YEAROFBIRTH_DECREMENT";
export const HANDLE_SORT_YEAROFBIRTH_DECREMENT_SUCCESS =
  "HANDLE_SORT_YEAROFBIRTH_DECREMENT_SUCCESS";
export const HANDLE_SORT_YEAROFBIRTH_DECREMENT_FAILED =
  "HANDLE_SORT_YEAROFBIRTH_DECREMENT_FAILED";

export const HANDLE_SORT_NAME_INCREMENT = "HANDLE_SORT_NAME_INCREMENT";
export const HANDLE_SORT_NAME_DECREMENT = "HANDLE_SORT_NAME_DECREMENT";
export const HANDLE_SORT_NAME_DECREMENT_SUCCESS =
  "HANDLE_SORT_NAME_DECREMENT_SUCCESS";
export const HANDLE_SORT_NAME_DECREMENT_FAILED =
  "HANDLE_SORT_NAME_DECREMENT_FAILED";

//#region search student
export const HANDLE_SEARCH_STUDENT = "HANDLE_SEARCH_STUDENT";
export const HANDLE_SEARCH_STUDENT_SUCCESS = "HANDLE_SEARCH_STUDENT_SUCCESS";
export const HANDLE_SEARCH_STUDENT_FAILED = "HANDLE_SEARCH_STUDENT_FAILED";
//#endregion

//#region edit student
export const HANDLE_EDIT_STUDENT = "HANDLE_EDIT_STUDENT";
export const HANDLE_EDIT_STUDENT_SUCCESS = "HANDLE_EDIT_STUDENT_SUCCESS";
export const HANDLE_EDIT_STUDENT_FAILED = "HANDLE_EDIT_STUDENT_FAILED";
//#endregion

//#region filter status
export const HANDLE_FILTER_STATUS = "HANDLE_FILTER_STATUS";
export const HANDLE_FILTER_STATUS_SUCCESS = "HANDLE_FILTER_STATUS_SUCCESS";
export const HANDLE_FILTER_STATUS_FAILED = "HANDLE_FILTER_STATUS_FAILED";
//#endregion
